### ISSUE TITLE
Demo for managing 12-hour time

### ISSUE THREAD

**Issue by hilibari** [openstatusHQ/time-picker#11]
This is a fantastic contribution to the community. Thanks for the sharing this.

It would be great if there was a clear path on how to accept 12-hour time. There is clearly some functionality for deal with 12-hour time baked into `time-picker-utils.tsx`. However, the implementation path is not super clear or defined. For instance, I can clearly there is a `isValid12Hour` function, which isn't being used.

It would be awesome to have an opinionated approach on how to manage 12-hour time!

**Comment by hilibari** [comment]
I just came across the `time-picker-12hour-demo.tsx` inside the repo. This is great. 

Maybe this demo should also be referenced on `time.openstatus.dev` (?) since one of the examples on the page supports 12-hour time. Doing so would make it easier for would-be users to find it. 

What do you think?

**Comment by mxkaske** [comment]
There is a demo for the `12h` time out under "Demo". Is it what you are refering to?

**Comment by hilibari** [comment]
I am referring to this demo: [time-picker-12hour-demo.tsx](https://github.com/openstatusHQ/time-picker/blob/90ec6033e549b5204b811fb4ca8a0734c3aa1701/src/components/time-picker/time-picker-12hour-demo.tsx). This demo uses [this implementation of `time-picker-utils.ts`](https://github.com/openstatusHQ/time-picker/blob/90ec6033e549b5204b811fb4ca8a0734c3aa1701/src/components/time-picker/time-picker-utils.ts).

The issue here is that, the `time-picker-utils.ts` used in the demo is very different from `time-picker-utils.ts` available on [`time.openstatus.dev/#time-picker-utils.tsx`](https://time.openstatus.dev/#time-picker-utils.tsx). This can lead to some confusion, especially for users who want to create time-inputs with using the 12hour format.

Adding a simple link to the demo would suffice IMHO.

**Comment by mxkaske** [comment]
Gosh you are right! The `utils` file should get updated/added.

**Comment by hilibari** [comment]
Glad I could contribute to an already great contribution! Much thanks again.

**Comment by Invito101** [comment]
I was just looking for this exact component, Thank you for updating the 12 hour format!
