### ISSUE TITLE
No <TimePeriodSelect> component on the docs

### ISSUE THREAD

**Issue by EthanL06** [openstatusHQ/time-picker#16]
I was trying to implement the `time-picker-12h-demo.tsx` component and saw that it required the`<TimePeriodSelect>` component. It would be nice if the docs included the code for the time period component instead of having to look through the repo.

**Comment by mohammadazeemwani** [comment]
> I was trying to implement the `time-picker-12h-demo.tsx` component and saw that it required the`<TimePeriodSelect>` component. It would be nice if the docs included the code for the time period component instead of having to look through the repo.

Where is the TimePeriodSelect component i can't find it in repo here

**Comment by D3OXY** [comment]
#17
