### ISSUE TITLE
Svelte version of time picker

### ISSUE THREAD

**Issue by 1bye** [openstatusHQ/time-picker#24]
I can’t find how to reach you otherwise than in GitHub issues

Inspired by yours, I’ve developed a Svelte adaptation of your TimePickerInput component, utilizing components from shadcn-svelte to provide a customizable and accessible time picker for Svelte applications. You can view the Svelte version here: [url](https://github.com/1bye/time-picker-svelte).

I am seeking your permission to share this Svelte adaptation publicly. Proper credit has been given to your original work in the documentation and repository. If you have any specific requirements or conditions for granting permission, please let me know, and I will be happy to accommodate them.

Thank you for your time and consideration. I look forward to your response.

**Comment by mxkaske** [comment]
Hey @1bye! Thanks for reaching out. Amazing you did the Svelte version! Open-Source ftw. 🚀

Of course, feel free to share it publicly!

**Comment by 1bye** [comment]
Thanks :)
