### ISSUE TITLE
 Bug in TimePickerInput Component - Unable to Enter 10, 11, or 12 for 12-Hour Times

### ISSUE THREAD

**Issue by zsh-eng** [openstatusHQ/time-picker#8]
## Description

When the time picker is set to the '12hours' format, it's impossible to enter times that start with 10, 11, or 12. This is due to the logic that automatically sets the second digit to 1 if the first digit is 0, as seen in the following code snippet:

```typescript
if (picker === "12hours" && flag && calculatedValue.slice(0, 1) === "0") {
 return "0" + key;
}
```

This logic prevents users from entering valid times in the 12-hour format that start with 10, 11, or 12.
For instance, when trying to type `11`.
After pressing `1`: input is `01`.
After pressing the second `1`: input is `01` as the conditional block is triggered and `01` is returned.

![Gif](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExa3A2ejZncDh3aXdqdmk1azJrNjVodmp5NWwwMGNnbGFvdDdjdTVjaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/HE5F8g2pnEnjNLZ45V/giphy.gif)

## Expected Behaviour

The component should allow users to enter any valid time in the 12-hour format, including those that start with 10, 11, or 12. The logic that automatically sets the second digit to 1 should not interfere with the ability to enter these times.

**Comment by agreen254** [comment]
@zsh-eng Thank you for the detailed explanation! I have opened a PR to fix this issue.
